/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//
function load()
{
    dashcode.setupParts();
    
    db_init();
    
    //disableExpenseButton('addExpenseBtn');
    //disableExpenseButton('addExpenseBtn-L');
}

function disableExpenseButton(buttonName)
{
    document.getElementById(buttonName).object.setEnabled(false);
}


//
// Function: flipToFront(event)
// Flip to the front view to show the normal utility view
//
function flipToFront(event)
{
    var views = document.getElementById('views');
    var front = document.getElementById('portrait');
    if (views && views.object && front) {
        views.object.setCurrentView(front, true);
    }
}

//
// Function: flipToSettings(event)
// Flip to the back view to present user customizable settings
//
function flipToSettings(event)
{
    var views = document.getElementById('views');
    var settings = document.getElementById('settings');
    if (views && views.object && settings) {
        views.object.setCurrentView(settings);
    }
}

function swapOrientation() 
{
    var views = document.getElementById('views');
    var v1 = document.getElementById('portrait');
    var v2 = document.getElementById('landscape');
	if (views && views.object && v1 && v2) {
        views.object.setCurrentView(views.object.getCurrentView() == v1 ? v2 : v1);
	}
}

function authenticate(event)
{
    // Insert Code Here
}


function addExpense(event)
{
    var expenseElem = document.getElementById('expenseField');
    db_addExpense(expenseElem.value);
}

function expenseValueChange(event)
{
    expenseButtonEnablement('addExpenseBtn', 'expenseField');
    expenseButtonEnablement('addExpenseBtn-L', 'expenseField-L');
}

function expenseButtonEnablement(buttonName, inputFieldName) 
{
    var addButton = document.getElementById(buttonName);
    var expenseField = document.getElementById(inputFieldName);
    addButton.object.setEnabled(expenseField.value != "");
}
